[BBN]
[BBN.params]
samples = 40000
seed = 2

[BBN.files]
task = "../data/Task_List.xlsx"
defect = "../data/Defect_Data.xlsx"
approx = "../data/sdlc_macro.xlsx"

[BBN.analysis]
type = 'precise' # 'precise': task level assessment, 'approx': stage level assessment
